# OpenCV Min, Max, Min-Max-Loc

Documentation:

https://docs.opencv.org/2.4/modules/core/doc/operations_on_arrays.html?#min

## Imports

In [18]:
import cv2
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

## Min, Max - 1

In [26]:
np.random.seed = 11
b = np.random.randint(0,256,(3,3))
b

array([[ 83, 101, 157],
       [  2,  91, 188],
       [222, 223,  96]])

In [29]:
cv2.min(b,100)

array([[ 83, 100, 100],
       [  2,  91, 100],
       [100, 100,  96]], dtype=int32)

In [30]:
cv2.max(b,100)

array([[100, 101, 157],
       [100, 100, 188],
       [222, 223, 100]], dtype=int32)

## Min, Max - 2

In [46]:
np.random.seed = 22
a1 = np.random.randint(0,2,(3,3))
a1

array([[1, 1, 0],
       [1, 1, 0],
       [0, 0, 1]])

In [47]:
a2 = np.copy(a1)

In [48]:
a2 = a2 + 1
a2[a2 > 1]=0
a2

array([[0, 0, 1],
       [0, 0, 1],
       [1, 1, 0]])

In [49]:
a1 + a2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [50]:
cv2.min(a1,a2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [51]:
cv2.max(a1,a2)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

## Min Max Loc